;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;																					;;
;;					PRESENTADO POR : JESUS MONSALVE ZERPA							;;
;;					C.I: 263737524													;;
;;					ESTE PROYECTO EN LENGUJE ASSEMBLER								;;
;;					CONSISTE EN HACER ENCENDER LOS LED SEGUN SE VA 					;;
;;					PRESIONANDO LOS BOTONES CORRESPONDIENTES						;;
;;																					;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

LIST P=16F84A
INCLUDE <P16F84A.INC>
__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _XT_OSC


		TIEMPO 	 EQU 0X0C
		TIEMPO2  EQU 0X0D

		org 0 


		BSF STATUS,RP0	; SE INGRESA AL BANCO1 PARA CONFIGURAR PUERTOS
		BSF TRISA , 1 	; DECLARA EL PUETO RA1 COMO ENTRADA 
		CLRF TRISB	 	; DECARA EL PUERTO RB1 COMO SALIDA
		BCF STATUS ,RP0 ; REGRESA A BANCO 0
		MOVLW B'00000001'


		MOVLW B'000001'
		MOVWF PORTB
		CALL RETARDO

		; INCIAMOS EL PROGRAMA
		
INICIO
		CALL RETARDO ;HACEMOS UN RETARDO
		CALL RETARDO; Y DOS RETARDOS YA Q ASI GRANTISAMOS NO ESTAR EN EFECTO REBOTE DEL BOTON 
		GOTO BOTON; AHORA SI ENTRAMOS EN UN CICLO SIN RETARDOS Q 100% ESTARA PENDIENTE SI ES PRECIONADO UN BOTON


;ESPERAMOS BOTON		
BOTON	
		BTFSS PORTA,0 ;MIRA SI EL PULSADOR 1 EN A0 ESTA EN 1
		GOTO LED0; SI ESTA EN 0 ENTRA EN LED0
		BTFSS PORTA,1 ;MIRA SI EL PULSADOR 2 EN A1 ESTA EN 1
		GOTO NOLED7 ;SI LO PRECIONAN ESTARA EN 0 Y ENTRA EN ESTE CICLO
		GOTO BOTON ; VOLVEMOS A CICLO BOTON A ESTAR PENDIENTES


NOLED7
		BTFSS PORTB,7;SI EL LED 7 ESTA ENCENDIDO
		GOTO NOLED6
		MOVLW B'01111111';;PONLO EN 0
		MOVWF PORTB
		GOTO INICIO


NOLED6
		BTFSS PORTB,6;SI EL LED 6 ESTA ENCENDIDO
		GOTO NOLED5
		MOVLW B'00111111';;PONLO EN 0
		MOVWF PORTB
		GOTO INICIO

NOLED5
		BTFSS PORTB,5;SI EL LED 5 ESTA ENCENDIDO
		GOTO NOLED4
		MOVLW B'00011111';PONLO EN 0
		MOVWF PORTB
		GOTO INICIO

NOLED4
		BTFSS PORTB,4;SI EL LED 4 ESTA ENCENDIDO
		GOTO NOLED3
		MOVLW B'00001111';PONLO EN 0
		MOVWF PORTB
		GOTO INICIO

NOLED3
		BTFSS PORTB,3;SI EL LED 3 ESTA ENCENDIDO
		GOTO NOLED2
		MOVLW B'00000111';PONLO EN 0
		MOVWF PORTB
		GOTO INICIO

NOLED2
		BTFSS PORTB,2;SI EL LED 2 ESTA ENCENDIDO
		GOTO NOLED1
		MOVLW B'00000011';PONLO EN 0
		MOVWF PORTB
		GOTO INICIO

NOLED1
		BTFSS PORTB,1;SI EL LED 1 ESTA ENCENDIDO
		GOTO NOLED0
		MOVLW B'00000001';PONLO EN 0
		MOVWF PORTB
		GOTO INICIO

NOLED0
		BTFSS PORTB,0;SI EL LED 0 ESTA ENCENDIDO
		GOTO INICIO
		MOVLW B'00000000';PONLO EN 0
		MOVWF PORTB
		GOTO INICIO



LED0
		BTFSC PORTB,0;SI EL LED 0 ESTA APAGADO
		GOTO LED1
		MOVLW B'00000001'
		MOVWF PORTB
		GOTO INICIO



LED1
		BTFSC PORTB,1;SI EL LED 1 ESTA APAGADO
		GOTO LED2
		MOVLW B'00000011'
		MOVWF PORTB
		GOTO INICIO

LED2
		BTFSC PORTB,2;SI EL LED 1 ESTA APAGADO
		GOTO LED3
		MOVLW B'00000111'
		MOVWF PORTB
		GOTO INICIO

LED3
		BTFSC PORTB,3;SI EL LED 1 ESTA APAGADO
		GOTO LED4
		MOVLW B'00001111'
		MOVWF PORTB
		GOTO INICIO

LED4
		BTFSC PORTB,4;SI EL LED 1 ESTA APAGADO
		GOTO LED5
		MOVLW B'00011111'
		MOVWF PORTB
		GOTO INICIO


LED5
		BTFSC PORTB,5;SI EL LED 1 ESTA APAGADO
		GOTO LED6
		MOVLW B'00111111'
		MOVWF PORTB
		GOTO INICIO


LED6
		BTFSC PORTB,6;SI EL LED 1 ESTA APAGADO
		GOTO LED7
		MOVLW B'01111111'
		MOVWF PORTB
		GOTO INICIO


LED7
		BTFSC PORTB,7;SI EL LED 1 ESTA APAGADO
		GOTO INICIO
		MOVLW B'11111111'
		MOVWF PORTB
		GOTO INICIO




RETARDO
		MOVLW D'255' ;CARGA W CON 255
		MOVFW TIEMPO ; TIEMPO ES IGUAL A 255
DEC 	DECFSZ TIEMPO; DECREMENTA A TIEMPO
		GOTO DEC1
		RETURN 

DEC1	MOVLW D'255' ;CARGA W CON 255
		MOVFW TIEMPO2 ; TIEMPO ES IGUAL A 255
DEC3 	DECFSZ TIEMPO2; DECREMENTA A TIEMPO
		GOTO DEC3
		GOTO DEC 
		END
END


